// <auto-generated />
namespace CatEpoch.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class CreateStoreProcAddGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateStoreProcAddGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201608012103261_CreateStoreProcAddGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
